version: "3"
services:
  app:
    hostname: app
    container_name: app
    image: sdsani/sb-docker-contact-service
    
  ui:
    image: sdsani/sb-docker-contact-ui
    container_name: ui
    environment:
      # way to override container port. In this case, I am overriding default 8081 to 8082.
      - SERVER_PORT=8082
      - CONTACTS_SERVER=http://app:8080/contacts
    ports:
      #host:container
      - "8080:8082"