name: CI Workflow

on:  
  workflow_dispatch:
  pull_request: 
    branches: [ main ]
    paths:
      - 'hello-spring-boot-docker/**'      
  
env:
  REPO_PATH: ${{github.actor}}
  ROOT_FOLDER: 'hello-spring-boot-docker'  

jobs:
  test_job:
    name: Test job just to run any test commands
    runs-on: ubuntu-latest
    steps:
      - name: Test echo commands
        run: |
          echo "1 : "$REPO_PATH
          echo "2 : "$ROOT_FOLDER
          echo "3 : "${{github.actor}}
          echo "4 : "$github.actor
