name: CI Workflow for Java application.

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - nonexistantbranchjustforexample
    #https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
    paths:
      - 'hello-spring-boot-docker/**'

jobs:
  # The first job lints the code base
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true

  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      # Cancel all matrix jobs if one of them fails
      fail-fast: true
      matrix:
        # our matrix for testing acros OSs
        #os: [windows-2019, ubuntu-latest]
        os: [ubuntu-latest]
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Set up JDK    
        uses: actions/setup-java@v1      
        with:        
          java-version: "11"
      - name: Verify java version
        run: java -version

      - name: Code Checout
        uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Run tests using gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: hello-spring-boot-docker

      - name: Build using Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: hello-spring-boot-docker

      #Be careful about following issue.
      #https://medium.com/prompt/trigger-another-github-workflow-without-using-a-personal-access-token-f594c21373ef
      #https://github.com/marketplace/actions/github-tag
      - name: Symantic tagging/verioning
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  cd:
    runs-on: ubuntu-latest
    strategy:
      # Cancel all matrix jobs if one of them fails
      fail-fast: true
    needs: ci
    steps:
      - name: Dummy step
        run: |
          echo "${{needs.ci.outputs.new_tag}}"
          
      - name: Set up JDK    
        uses: actions/setup-java@v1      
        with:        
          java-version: "11"
          
      - name: Code Checout                             
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Build docker container using gradle/springboot
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage
          build-root-directory: hello-spring-boot-docker
       
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Tag and push docker images
        run: |
          echo $GITHUB_REPOSITORY
          echo $needs.ci.outputs.new_tag
          echo ${{needs.ci.outputs.new_tag}}
          docker images
          #docker tag sdsani/hello-spring-boot-docker hello-spring-boot-docker/latest 
          docker tag sdsani/hello-spring-boot-docker:latest hello-spring-boot-docker:"${{needs.ci.outputs.new_tag}}" 
          docker images
          #docker push sdsani/hello-spring-boot-docker:latest
          #docker push sdsani/hello-spring-boot-docker:"${{needs.ci.outputs.new_tag}}"
