name: CI Workflow for Java application.

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - nonexistantbranchjustforexample
    #https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
    paths:
      - 'hello-spring-boot-docker/**'

jobs:
  # The first job lints the code base
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true

  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      # Cancel all matrix jobs if one of them fails
      fail-fast: true
      matrix:
        # our matrix for testing acros OSs
        #os: [windows-2019, ubuntu-latest]
        os: [ubuntu-latest]
    steps:
      - name: Set up JDK    
        uses: actions/setup-java@v1      
        with:        
          java-version: "11"
      - name: Verify java version
        run: java -version

      - name: Code Checout
        uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Run tests using gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: hello-spring-boot-docker

      - name: Build using Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: hello-spring-boot-docker

      #Be careful about following issue.
      #https://medium.com/prompt/trigger-another-github-workflow-without-using-a-personal-access-token-f594c21373ef
      #https://github.com/marketplace/actions/github-tag
      - name: Symantic tagging/verioning
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use latest tag
        run: |
          echo 'XXXXXX: $env:RUNNER_OS.'
          echo {{ $steps.tag_version.outputs.new_tag }}
          echo "=====> {{ $steps.tag_version.outputs.new_tag }}"
          echo "=====> {{ $steps.tag_version.outputs.release_type }}"
          echo "$steps.tag_version.outputs.new_tag"
          echo $steps.tag_version.outputs.new_tag
