name: CI Workflow for Java application.

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - nonexistantbranchjustforexample
    #https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
    paths:
      - 'hello-spring-boot-docker/**'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from CI pipeline."
  actual_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "More to come."
      - run: pwd
      - name: Execute gradle test
        run: ./hello-spring-boot-docker/gradlew test 
      - name: Execute gradle build
        run: ./hello-spring-boot-docker/gradlew build
      - run: ls -al
      - run: echo "More to come."
