on:  
  pull_request: 
    branches: [ main ]
    paths:
      - 'hello-spring-boot-docker/**'      

  workflow_dispatch:
  
env:
  REPO_PATH: ${{github.actor}}
  ROOT_FOLDER: 'hello-spring-boot-docker'  

jobs:
  test_job:
    name: Test job just to run any test commands
    #if: ${{inputs.event_name}} == 'pull_request'
    runs-on: ${{ matrix.os }}
    strategy:
      # Cancel all matrix jobs if one of them fails
      fail-fast: true
      matrix:
        # our matrix for testing acros OSs
        os: [ubuntu-latest]
    steps:
      - name: Test echo commands
        run: |
          echo "1 : "$REPO_PATH
          echo "2 : "$ROOT_FOLDER
          echo "3 : "${{github.actor}}
          echo "4 : "$github.actor
