name: CI Workflow for Java application.

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - nonexistantbranchjustforexample
    #https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
    paths:
      - 'hello-spring-boot-docker/**'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from CI pipeline."
  actual_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK    
        uses: actions/setup-java@v1      
        with:        
          java-version: "11"
      - name: Verify java version
        run: java -version

      - name: Code Checout
        uses: actions/checkout@v3
        with:
            fetch-depth:0

      - name: Run tests using gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: hello-spring-boot-docker

      - name: Build using Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: hello-spring-boot-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: List docker images before build
        run: docker images

      - name: Build docker container using gradle/springboot
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage
          build-root-directory: hello-spring-boot-docker
      - name: List docker images after build
        run: docker images

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to docker using docker command
        run: docker push

      #https://github.com/marketplace/actions/git-semantic-version
      - name: Symantic tagging
        run: echo "More to come. https://github.com/marketplace/actions/git-semantic-version"
