name: CI + CD

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  
  pull_request: 
    branches: [ main ]
    paths:
      - 'hello-spring-boot-docker/**'
  
  push: 
    branches: [ main ]
    paths:
      - 'hello-spring-boot-docker/**'
      
  workflow_dispatch:
  
env:
  REPO_PATH: "${{ github.actor }}/"
  ROOT_FOLDER: 'hello-spring-boot-docker'  
  
jobs:

  CI:
    uses: ./.github/workflows/ci.yaml
    name: CI
    if: github.event_name == 'pull_request'
    with:
      event_name: ${{github.event_name}} 
      event_ref: ${{github.event.ref}}
  
  WE:
   name: Anything else that we should do before merge
   if: github.event_name == 'pull_request'
   runs-on: ubuntu-latest
   needs: [CI]   
   
   steps:
     - run: |
         echo "What else should be done before merge"

  CD:
    name: CD
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    strategy:
      # Cancel all matrix jobs if one of them fails
      fail-fast: true
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      
    steps:          
      - name: Set up JDK    
        uses: actions/setup-java@v1      
        with:        
          java-version: "11"
          
      - name: Code Checout                             
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
            
      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1
        
      - name: Symantic tagging/verioning
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          custom_release_rules: | 
            bug:patch:Bug Fixes,
            chore:patch:Chores,            
            perf:patch:Performance Improvement,
            ci:patch:Continuous Integration,
            docs:patch:Documentation Improvement,
            style:patch:Code Style,
            refactor:patch:Refactoring/TODO's,
            test:patch:Tests,
            feat:minor:New Functionality,
            feature:minor:New Functionality,
            minor_upd:minor:Minor Update,
            major_upd:major:Major Update,
            major:major:Major Update
  
      - name: Build docker image
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage
          build-root-directory: hello-spring-boot-docker
       
      - name: Docker login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Tag and push docker images
        run: |
          #https://pakstech.com/blog/github-actions-workflow-commands/
          echo $GITHUB_REPOSITORY
          echo $new_tag
          echo ${{ github.event.repository.name }}
          docker tag ${{env.REPO_PATH}}${{env.ROOT_FOLDER}}:latest ${{env.REPO_PATH}}${{env.ROOT_FOLDER}}:$new_tag 
          docker images
          docker push ${{env.REPO_PATH}}${{env.ROOT_FOLDER}}:latest
          docker push ${{env.REPO_PATH}}${{env.ROOT_FOLDER}}:$new_tag
        env:
          new_tag: ${{steps.tag_version.outputs.new_tag}}
  
  Deploy:
    uses: ./.github/workflows/deploy.yaml
    name: Deploy code to environments
    needs: [CD]
    with:
      event_name: ${{github.event_name}} 
      event_ref: ${{github.event.ref}}
    secrets:
      registry_username: ${{secrets.REGISTRY_USERNAME}}
      registry_password: ${{secrets.REGISTRY_PASSWORD}}
