name: CI + CD

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  
  pull_request: 
    branches: [ main ]
    paths:
      - 'hello-spring-boot-docker/**'
  
  push: 
    branches: [ main ]
    paths:
      - 'hello-spring-boot-docker/**'
      
  workflow_dispatch:
  
env:
  REPO_PATH: "${{ github.actor }}/"
  ROOT_FOLDER: 'hello-spring-boot-docker'  
  
jobs:

  ci:
    uses: ./.github/workflows/ci.yaml
    name: CI
    if: github.event_name == 'pull_request'
    with:
      event_name: ${{github.event_name}} 
      event_ref: ${{github.event.ref}}

  call_cd:
    uses: ./.github/workflows/cd.yaml
    with:
      event_name: ${{github.event_name}} 
      event_ref: ${{github.event.ref}}
    secrets:
      dh_username: ${{secrets.DOCKERHUB_USERNAME}}
      dh_token: ${{secrets.DOCKERHUB_TOKEN}}
  
  test_job:
    name: Test job to verify new_tag
    if: github.event_name == 'push'
    needs: [call_cd]
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "First: "${{needs.call_cd.outputs.new_tag}}
          echo "Second: "${{needs.cd.outputs.new_tag}}

  deploy:
    uses: ./.github/workflows/deploy.yaml
    name: Deploy code to environments
    needs: [call_cd]
    with:
      event_name: ${{github.event_name}} 
      event_ref: ${{github.event.ref}}
      tag_name: ${{needs.cd.outputs.new_tag}}
    secrets:
      registry_username: ${{secrets.REGISTRY_USERNAME}}
      registry_password: ${{secrets.REGISTRY_PASSWORD}}
