name: CI + CD

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  
  pull_request: 
    branches: [ main ]
    paths:
      - 'hello-spring-boot-docker/**'
  
  push: 
    branches: [ main ]
    paths:
      - 'hello-spring-boot-docker/**'
      
  workflow_dispatch:
  
env:
  REPO_PATH: "${{ github.actor }}/"
  ROOT_FOLDER: 'hello-spring-boot-docker'  
  
jobs:

  CI:
    uses: ./.github/workflows/ci.yaml
    name: CI
    if: github.event_name == 'pull_request'
    with:
      event_name: ${{github.event_name}} 
      event_ref: ${{github.event.ref}}
  
  WE:
   name: Anything else that we should do before merge
   if: github.event_name == 'pull_request'
   runs-on: ubuntu-latest
   needs: [CI]   
   
   steps:
     - run: |
         echo "What else should be done before merge"

  CD:
    uses: ./.github/workflows/cd.yaml
    name: CD
    if: github.event_name == 'push'
    with:
      event_name: ${{github.event_name}} 
      event_ref: ${{github.event.ref}}
    secrets:
      dh_username: ${{secrets.DOCKERHUB_USERNAME}}
      dh_token: ${{secrets.DOCKERHUB_TOKEN}}
  
  Deploy:
    uses: ./.github/workflows/deploy.yaml
    name: Deploy code to environments
    needs: [CD]
    with:
      event_name: ${{github.event_name}} 
      event_ref: ${{github.event.ref}}
      tag_name: ${{needs.cd.outputs.new_tag}}
    secrets:
      registry_username: ${{secrets.REGISTRY_USERNAME}}
      registry_password: ${{secrets.REGISTRY_PASSWORD}}
