name: Deploy Base
on: 
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      env_url:
        required: true
        type: string

env:
  REPO_PATH: "${{ github.actor }}/"
  ROOT_FOLDER: 'hello-spring-boot-docker' 

jobs:
  DeployBase:
    runs-on: ubuntu-latest
    environment: 
      name: ${{env_name}}
      url: ${{env_url}}    
    strategy:
      # Cancel all matrix jobs if one of them fails
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy
        run: |
          echo ${{env.GITHUB_EVENT_NAME}}
          docker pull ${{env.REPO_PATH}}${{env.ROOT_FOLDER}}
          docker images
          echo "WIP: Deploy to development steps not implemented yet."
          echo "New tag created in CD passed to Deploy : "${{needs.cd.outputs.new_tag}}
