# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy to GKE

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:

  deploy_service:
    uses: ./.github/workflows/gke-deploy-service.yaml
    name: Deploy Contact Service
    with:
      MANIFEST_PATH: sb-docker-contact-cloud/k8s-app-deployment.yaml
      ROLLBACK: false
    secrets:
      GKE_PROJECT: ${{secrets.GKE_PROJECT}}
      GKE_SA_KEY: ${{secrets.GKE_SA_KEY}}

  deploy_ui:
    needs: [deploy_service]
    uses: ./.github/workflows/gke-deploy-service.yaml
    name: Deploy Contact UI
    with:
      MANIFEST_PATH: sb-docker-contact-cloud/k8s-app-ui-deployment.yaml
      ROLLBACK: false
    secrets:
      GKE_PROJECT: ${{secrets.GKE_PROJECT}}
      GKE_SA_KEY: ${{secrets.GKE_SA_KEY}}
