# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Rollback from GKE

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:

  rollback_service:
    needs: [rollback_ui]
    uses: ./.github/workflows/gke-deploy-service.yaml
    name: Delete Contact Service
    with:
      MANIFEST_PATH: sb-docker-contact-cloud/k8s-app-deployment.yaml
      ACTION: ROLLBACK
    secrets:
      GKE_PROJECT: ${{secrets.GKE_PROJECT}}
      GKE_SA_KEY: ${{secrets.GKE_SA_KEY}}

  rollback_ui:
    uses: ./.github/workflows/gke-deploy-service.yaml
    name: Delete Contact UI
    with:
      MANIFEST_PATH: sb-docker-contact-cloud/k8s-app-deployment.yaml
      ACTION: ROLLBACK
    secrets:
      GKE_PROJECT: ${{secrets.GKE_PROJECT}}
      GKE_SA_KEY: ${{secrets.GKE_SA_KEY}}