name: CI Workflow for Java application.

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  pull:
    branches:
      - main
    #https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
    paths:
      - 'hello-spring-boot-docker/**'

env:
  REPO_PATH: 'sdsani/'
  ROOT_FOLDER: 'hello-spring-boot-docker'  
  
jobs:
  # The first job lints the code base
  test-job:
    name: List contents
    runs-on: ubuntu-latest
    steps:
      - name: Pre list
        run: |
          ls -al
          
      - name: Code Checout
        uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: List folder
        run: |
          ls -al
          echo "============================================================================================="
          ls hello-spring-boot-docker -al 
