name: CI Workflow to build container upon tagging

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
    branches:
      - main
      - nonexistantbranchjustforexample
    #https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
    #Following is not necessary since it will be controlled thru ci flow.
    paths:
      - 'hello-spring-boot-docker/**'
    #Run this workflow if tag starting with v.
    tags:
      - 'v*'
jobs:
  #https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#create
  build_container:
    runs-on: ubuntu-latest
    #Following is redundent, just putting it for the sake of example.
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Code Checout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build docker container using gradle/springboot    
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage
          build-root-directory: hello-spring-boot-docker
          
      - name: Login to DockerHub                                
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      #https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
      - name: Push to docker using docker command
        run: |
          docker images 
          echo ${{ github.event.release.tag_name }}
          echo ${{ env.RELEASE_VERSION}}
          #docker push sdsani/hello-spring-boot-docker

  deploy-app:
    name: Deploy job
    runs-on: ubuntu-latest
    needs: [build_container]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy step
        run: echo "Deploy not implemented yet"
