name: Workflow to trigger build on tag.

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
    branches:
      - main
    #Run this workflow if tag starting with v.
    tags:
      - 'v*'
jobs:
  display_info:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION}}
          
      - run: |
         echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}"
