name: Test workflow

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  pull_request: 
    branches: [ main ]
  
  push:
    branches:
      - main
      
jobs:
  onlyrunonpush:
    name: Test execution only on for push request.
    runs-on: ubuntu-latest
    if: $GITHUB_EVENT_NAME == 'push'
    steps:
      - name: List for push
        run: |
          ls -al
          echo "This job should run only only on Push request. Current event is : $GITHUB_EVENT_NAME"
        
  onlyrunonpull:
    name: Test execution only on for pull request.
    runs-on: ubuntu-latest
    if: $GITHUB_EVENT_NAME == 'pull_request'
    steps:
      - name: List for pull
        run: |
          ls -al
          echo "This job should run only only on Pull request. Current event is : $GITHUB_EVENT_NAME "
        
  runonbothpushandpull:
    name: Test execution on both pull and push requests.
    runs-on: ubuntu-latest
    if: $GITHUB_EVENT_NAME == 'pull_request' || $GITHUB_EVENT_NAME == 'push'
    steps:
      - name: List
        run: |
          ls -al
          echo "This job should run for both push and pull. Current event is : $GITHUB_EVENT_NAME "
