name: Test workflow

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  pull_request: 
    branches: [ main ]
  
  push:
    branches:
      - main
      
jobs:
  onlyrunonpull:
    name: Test execution only on for pull request.
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: List for pull
        run: |
          ls -al
          echo "This job should run only only on Pull request. Current event is : $GITHUB_EVENT_NAME "
        
  runonbothpushandpull:
    name: Test execution on both pull and push requests.
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    steps:
      - name: List
        run: |
          ls -al
          echo "This job should run for both push and pull. Current event is : $GITHUB_EVENT_NAME "
      - name: Condition at step
        if: github.event_name == 'push'
        run: |
          echo "<<<<<<<< Step execution >>>>>>>>"
          
  param_passing:   
    name: Example to demo parameter passing between steps
    runs-on: ubuntu-latest
    steps:
      - name: First step to generate params
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          
      - name: Now read the values
        run: |
          echo "${{steps.tag_version.outputs.new_tag}}"
          echo "${{steps.tag_version.outputs.previous_tag}}"
        
